### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by ILikeToHelp** [dullhunk/book#9]
The link to the "figure 1: social media explained with donuts" doesn't work on https://github.com/dullhunk/book/blob/master/careers-lab/cvapps/cv-general.md

Was tempted to share a new link or delete the link in a new PR, but decided to open the issue as you might just re-link the proper image if you have the access.

**Comment by dullhunk** [comment]
Thanks @ILikeToHelp its moved to [cdyf.me/debugging.html](https://www.cdyf.me/debugging.html) all contributions welcome, both small and big see [cdyf.me/#contributing](https://cdyf.me/#contributing)
